version: '3.9'

services:
  betsports:
    build: .
    ports:
      - 8080:8000
    env_file:
      - betsports/.env
    command: ["bash", "startapp.sh"]
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: villegasjuan@yahoo.com
    networks:
      - internal
    depends_on:
      - broker
  
  worker:
    build: .
    env_file:
      - betsports/.env
    command: ["bash", "startworker.sh"]
    environment:
        DJANGO_SUPERUSER_USERNAME: admin
        DJANGO_SUPERUSER_PASSWORD: admin
        DJANGO_SUPERUSER_EMAIL: villegasjuan@yahoo.com
    networks:
      - internal
    depends_on:
      - broker

  broker:
    build:
      dockerfile: Dockerfile-broker
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - internal

networks:
  internal:
    driver: bridge